version: '3.8'

services:

  asterisk:
    build:
      context: ./asterisk
    image: asterisk:0.0.3
    volumes:
      - asterisk_run:/var/lib/run/asterisk
      - asterisk_etc:/etc/asterisk

  mariadb:
    image: mariadb:11.1.2
    hostname: mariadb
    restart: always
    env_file:
      - .env
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb/my-resolve.cnf:/etc/mysql/mariadb.conf.d/my-resolve.cnf:ro
      #- db:/var/lib/mysql

  adminer:
    image: adminer:4.8.1
    restart: always
    ports:
      - 8080:8080
    environment:
      - ADMINER_DEFAULT_SERVER=mariadb
    depends_on:
      - mariadb 

  freepbx:
    build:
      context: ./freepbx

    volumes:
      - asterisk_run:/var/lib/run/asterisk
      - asterisk_etc:/etc/asterisk
      - freepbx_www:/var/www/html
    depends_on:
      - asterisk
      - mariadb 
    ports:
      - 9000:9000
    env_file:
      - .env
    command: ["/usr/sbin/php-fpm7.4"]
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - freepbx_www:/var/www/html
    ports:
      - 80:80
    depends_on:
      - freepbx 


volumes:
  asterisk_etc:
  asterisk_run:
  freepbx_www:
  db:

